import Foundation

/// Bilingual golden fixtures for ``IntentExtractorGoldenHarnessTests``.
enum IntentExtractorGoldenFixtures {
    static let all: [IntentExtractorGoldenFixture] =
        englishFixtures + chineseFixtures + mixedFixtures + llmReplayFixtures
}

private extension IntentExtractorGoldenFixtures {

    static let englishFixtures: [IntentExtractorGoldenFixture] = [
        .init(
            id: "en.local_service.1",
            language: "english",
            category: "local_service_search",
            inputText: "Find me a plumber in Austin for a leak repair this Saturday afternoon.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: ["find"],
            expectedAnyQueryIntentClasses: ["providerSearch", "generalDiscovery", "capabilitySearch"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["homeService", "general"],
            expectedHaystackSubstrings: ["plumber", "austin"],
            expectedSummaryLine: "EN local service: plumber + Austin + Saturday window",
            validationMode: .strict
        ),
        .init(
            id: "en.commercial_offer.1",
            language: "english",
            category: "commercial_offer_product_search",
            inputText: "Looking for a used MacBook Pro under 1200 dollars shipped to Canada.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: ["find", "source"],
            expectedAnyQueryIntentClasses: ["offerSearch", "generalDiscovery", "providerSearch"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["product", "general"],
            expectedHaystackSubstrings: ["macbook"],
            expectedSummaryLine: "EN commercial product: MacBook + budget + ship",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.professional.1",
            language: "english",
            category: "professional_freelancer_search",
            inputText: "Need a freelance Solidity auditor for a two week codebase review.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: ["capabilitySearch", "providerSearch", "generalDiscovery"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["professionalService", "general"],
            expectedHaystackSubstrings: ["solidity"],
            expectedSummaryLine: "EN professional: Solidity auditor",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.social_person.1",
            language: "english",
            category: "social_person_discovery",
            inputText: "Find people nearby who want a tennis partner for weekday evenings.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: ["find"],
            expectedAnyQueryIntentClasses: ["socialAffinitySearch", "generalDiscovery", "collaborationSearch", "providerSearch"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["general"],
            expectedHaystackSubstrings: ["tennis"],
            expectedSummaryLine: "EN social: tennis partner",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.interest_affinity.1",
            language: "english",
            category: "interest_affinity_discovery",
            inputText: "Looking for someone to join a weekend hiking group in the Bay Area.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: ["find"],
            expectedAnyQueryIntentClasses: ["socialAffinitySearch", "generalDiscovery", "collaborationSearch", "providerSearch"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["general"],
            expectedHaystackSubstrings: ["hiking"],
            expectedSummaryLine: "EN affinity: hiking group",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.trusted_contact.1",
            language: "english",
            category: "trusted_contact_direct_person_search",
            inputText: "Message John Smith from my contacts about the contract renewal timeline.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["john"],
            expectedSummaryLine: "EN direct/contact phrasing (may route non-search)",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.time_sensitive.1",
            language: "english",
            category: "time_sensitive_request",
            inputText: "Need an emergency locksmith in Seattle tonight before 10pm.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: ["providerSearch", "generalDiscovery"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["general", "homeService"],
            expectedHaystackSubstrings: ["locksmith", "tonight"],
            expectedSummaryLine: "EN time-sensitive: locksmith + tonight",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.location_sensitive.1",
            language: "english",
            category: "location_sensitive_request",
            inputText: "Roofing contractors within 15 miles of zip 98101.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: ["providerSearch", "generalDiscovery"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["homeService", "general"],
            expectedHaystackSubstrings: ["roof", "98101"],
            expectedSummaryLine: "EN location: roofing + zip",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.remote_online.1",
            language: "english",
            category: "remote_online_request",
            inputText: "Remote Spanish tutor for conversational practice on weekday mornings EST.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: ["providerSearch", "capabilitySearch", "generalDiscovery"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["general", "professionalService"],
            expectedHaystackSubstrings: ["spanish", "tutor"],
            expectedSummaryLine: "EN remote: Spanish tutor",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.budget_price.1",
            language: "english",
            category: "budget_price_constrained_request",
            inputText: "Wedding photographer under 3000 dollars near Chicago next spring.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: ["providerSearch", "offerSearch", "generalDiscovery"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["general", "professionalService"],
            expectedHaystackSubstrings: ["photographer", "3000"],
            expectedSummaryLine: "EN budget: wedding photographer cap",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.availability.1",
            language: "english",
            category: "availability_constrained_request",
            inputText: "Yoga instructor for private sessions only Sundays before noon.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: ["providerSearch", "generalDiscovery", "capabilitySearch"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["general", "professionalService"],
            expectedHaystackSubstrings: ["yoga", "sunday"],
            expectedSummaryLine: "EN availability: yoga Sundays",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.vague.1",
            language: "english",
            category: "vague_needs_clarification",
            inputText: "Can someone help with something important?",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: ["needsClarification", "underSpecified", "ready"],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: [],
            expectedSummaryLine: "EN vague ask (readiness varies)",
            validationMode: .auditOnly
        ),
        .init(
            id: "en.multi_constraint.1",
            language: "english",
            category: "multi_constraint_request",
            inputText: "Find a bilingual family law lawyer in Miami for a first consultation before Friday with budget under 500 dollars per hour.",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: ["find"],
            expectedAnyQueryIntentClasses: ["providerSearch", "generalDiscovery", "capabilitySearch"],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: ["professionalService", "general"],
            expectedHaystackSubstrings: ["lawyer", "miami", "friday"],
            expectedSummaryLine: "EN multi: lawyer + Miami + time + rate",
            validationMode: .auditOnly
        ),
    ]

    static let chineseFixtures: [IntentExtractorGoldenFixture] = [
        .init(
            id: "zh.local_service.1",
            language: "chinese",
            category: "local_service_search",
            inputText: "我需要在周六下午在奥斯汀找一位水管工修理漏水。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["奥斯汀", "水管"],
            expectedSummaryLine: "ZH local service (Chinese plumbing ask)",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.commercial_offer.1",
            language: "chinese",
            category: "commercial_offer_product_search",
            inputText: "我想买一台二手 MacBook Pro，预算八千人民币以内，可以邮寄到上海。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["macbook", "上海"],
            expectedSummaryLine: "ZH product purchase + ship to Shanghai",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.professional.1",
            language: "chinese",
            category: "professional_freelancer_search",
            inputText: "需要一位熟悉 Solidity 的自由职业安全审计员，两周内完成代码审查。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["solidity"],
            expectedSummaryLine: "ZH professional Solidity auditor",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.social_person.1",
            language: "chinese",
            category: "social_person_discovery",
            inputText: "想找附近晚上一起打网球的人。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["网球"],
            expectedSummaryLine: "ZH social tennis partner",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.interest_affinity.1",
            language: "chinese",
            category: "interest_affinity_discovery",
            inputText: "有没有周末在湾区一起徒步的新手小组？",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["徒步", "湾区"],
            expectedSummaryLine: "ZH hiking affinity Bay Area",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.trusted_contact.1",
            language: "chinese",
            category: "trusted_contact_direct_person_search",
            inputText: "给我通讯录里的张伟发消息，确认合同进展。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["张伟"],
            expectedSummaryLine: "ZH contact-specific message",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.time_sensitive.1",
            language: "chinese",
            category: "time_sensitive_request",
            inputText: "今晚十点前需要在西雅图市中心找紧急开锁师傅。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["西雅图", "今晚"],
            expectedSummaryLine: "ZH urgent locksmith Seattle tonight",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.location_sensitive.1",
            language: "chinese",
            category: "location_sensitive_request",
            inputText: "在邮编 98101 附近十五英里内找屋顶维修承包商。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["98101", "屋顶"],
            expectedSummaryLine: "ZH roofing zip radius",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.remote_online.1",
            language: "chinese",
            category: "remote_online_request",
            inputText: "需要远程的西班牙语口语陪练老师，工作日早上（美国东部时间）。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["西班牙语", "远程"],
            expectedSummaryLine: "ZH remote Spanish tutor",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.budget_price.1",
            language: "chinese",
            category: "budget_price_constrained_request",
            inputText: "明年春天在芝加哥附近找婚礼摄影师，预算不超过三千美元。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["芝加哥", "婚礼", "摄影师"],
            expectedSummaryLine: "ZH wedding photographer budget",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.availability.1",
            language: "chinese",
            category: "availability_constrained_request",
            inputText: "只想在周日上午十二点前预约私人瑜伽教练上门。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["瑜伽", "周日"],
            expectedSummaryLine: "ZH yoga Sunday window",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.vague.1",
            language: "chinese",
            category: "vague_needs_clarification",
            inputText: "能不能帮我处理一件很重要的事？",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: [],
            expectedSummaryLine: "ZH vague ask",
            validationMode: .auditOnly
        ),
        .init(
            id: "zh.multi_constraint.1",
            language: "chinese",
            category: "multi_constraint_request",
            inputText: "在迈阿密找一位双语家庭法律师，周五前要完成首次咨询，每小时费用不超过五百美元。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["迈阿密", "律师", "周五"],
            expectedSummaryLine: "ZH multi lawyer Miami time rate",
            validationMode: .auditOnly
        ),
    ]

    static let mixedFixtures: [IntentExtractorGoldenFixture] = [
        .init(
            id: "mx.local_bilingual.1",
            language: "mixed",
            category: "local_service_search",
            inputText: "上海 Pudong 周末 need a certified electrician 上门检查电路。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["electrician", "上海"],
            expectedSummaryLine: "Mixed CN/EN electrician Shanghai weekend",
            validationMode: .auditOnly
        ),
        .init(
            id: "mx.remote_budget.1",
            language: "mixed",
            category: "remote_online_request",
            inputText: "Remote UI designer needed, 远程工作，预算 budget 5000 RMB 以内。",
            llmFlatSummaryJSON: nil,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["remote", "designer", "5000"],
            expectedSummaryLine: "Mixed remote designer budget",
            validationMode: .auditOnly
        ),
    ]

    /// Golden flat-summary JSON replayed through ``LLMOpenEndedSearchIntentExtractor`` (mapper only).
    static let llmReplayFixtures: [IntentExtractorGoldenFixture] = [
        .init(
            id: "llm.replay.roofer_flat.1",
            language: "english",
            category: "local_service_search",
            inputText: "Find me a roofer in Aurora tomorrow at 2:30pm.",
            llmFlatSummaryJSON: """
            {"raw":"Find me a roofer in Aurora tomorrow at 2:30pm.","object":"roofer","need":null,"place":"Aurora","time":"tomorrow at 2:30pm","budget":null,"commercial":null,"mods":[],"hard":["Aurora","tomorrow at 2:30pm"],"soft":[],"gaps":[],"confidence":0.9}
            """,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["roofer", "aurora"],
            expectedSummaryLine: "LLM flat replay: roofer + Aurora (mapper path)",
            validationMode: .strict
        ),
        .init(
            id: "llm.replay.shanghai_macbook.1",
            language: "chinese",
            category: "commercial_offer_product_search",
            inputText: "二手 MacBook Pro 八千以内邮寄上海",
            llmFlatSummaryJSON: """
            {"raw":"二手 MacBook Pro 八千以内邮寄上海","object":"MacBook Pro","need":null,"place":"上海","time":null,"budget":"8000 CNY","commercial":null,"mods":["二手","邮寄"],"hard":["上海"],"soft":[],"gaps":[],"confidence":0.82}
            """,
            expectedAnyIntentKinds: [],
            expectedAnyQueryIntentClasses: [],
            expectedAnySurfacePreferences: [],
            expectedReadiness: [],
            expectedDomainCategories: [],
            expectedHaystackSubstrings: ["macbook", "上海"],
            expectedSummaryLine: "LLM flat replay: MacBook + Shanghai (Chinese surface text)",
            validationMode: .auditOnly
        ),
    ]
}
